---
name: firefox-ui-functional-remote (test-windows10-64-asan)
on:
  push:
    branches:
      - main
jobs:
  opt-firefox-ui-functional-remote-e10s:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: mounts
        run: |
          curl -L https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KOxlTjcQRt6yK9EKP58Kjw/artifacts/public/build/mozharness.zip --output mozharness.zip
          7z x -omozharness mozharness.zip
          curl -L https://hg.mozilla.org/try/raw-file/d6f981475764dc0fab78bc4f5d8d4601e1ca21f6/taskcluster/scripts/run-task --output ./run-task
          curl -L https://hg.mozilla.org/try/raw-file/d6f981475764dc0fab78bc4f5d8d4601e1ca21f6/taskcluster/scripts/misc/fetch-content --output ./fetch-content
      - name: dependencies
        run: |
          python -m pip install --upgrade zstandard
          python -m pip install --upgrade certifi
      - name: test
        env:
          TASKCLUSTER_ROOT_URL: https://firefox-ci-tc.services.mozilla.com
          PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
          MOZ_FETCHES: "[{\"artifact\": \"public/build/fix-stacks.tar.bz2\", \"extract\": true, \"task\": \"MfZ57fS0RJq2SDEaJuIF-w\"}, {\"artifact\": \"public/build/minidump_stackwalk.tar.xz\", \"extract\": true, \"task\": \"RJVVjsRKS_WpChQ-NujlIw\"}]"
          TRY_SELECTOR: "chooser"
          MOZ_SCM_LEVEL: "1"
          GECKO_HEAD_REV: "d6f981475764dc0fab78bc4f5d8d4601e1ca21f6"
          MOZ_AUTOMATION: "1"
          TRY_COMMIT_MSG: ""
          MOZ_FETCHES_DIR: "fetches"
          SCCACHE_DISABLE: "1"
          GECKO_HEAD_REPOSITORY: "https://hg.mozilla.org/try"
          EXTRA_MOZHARNESS_CONFIG: "{\"installer_url\": \"https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KOxlTjcQRt6yK9EKP58Kjw/artifacts/public/build/target.zip\", \"test_packages_url\": \"https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KOxlTjcQRt6yK9EKP58Kjw/artifacts/public/build/target.test_packages.json\"}"
        run: |
          python run-task -- python -u mozharness\scripts\firefox_ui_tests\functional.py --cfg mozharness\configs\firefox_ui_tests\taskcluster_windows.py --tag remote --setpref=media.peerconnection.mtransport_process=false --setpref=network.process.enabled=false --download-symbols ondemand
